server:
  port: 8081
spring:
  application:
    name: shortURL
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shorturl?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zgb159632
  # 邮件发送
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: 15915912344@163.com
    password: XZYFVFEKIQZSMGBO
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
  # redis
  data:
    redis:
      host: 192.168.130.58
      port: 6379
      password: zgb159632
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.shorturl.Entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
      column-underline: true
logging:
  level:
    com.example.shorturl: debug